var GAME_LEVELS = [
  ["                           o                                                    ",
   "                          ooo                                                   ",
   "                           o                                                    ",
   "                      o         o                  y                            ",
   "                       xx!!!!!xx                              f                 ",
   "                        xx!!!xx                              fff     +          ",
   "                          x!x                                                   ",
   "        f                  v              y        xxx      xx                 ",
   "       fff                            o o      xx    x       ox                 ",
   "      fffff                             =               x       ox              ",
   "                      xx   o   xxxx       xx       x        x                   ",
   "                      xx       x    x      x   x  ox        x        y      xx  ",
   "  xx            +     xx            xo     x      xx                      ff x  ",
   "  x                   xxo   x       x      x!!!!!!!x                         x  ",
   "  x                   xx    x       o      x!!!!!!!x                       * x  ",
   "  x          xxxx     xxo   x            + xxxxxxxxx  +   y                  x  ",
   "  x  @       xxxx     xx    x                                     xxxxx      x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx  x  xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                   xxxxxxx                         f       fff    ",
   "                                                                xxxx     xxxx                     fff      ffff   ",
   "                                      xxxxxxxxxxxxxx                   y                                          ",
   "                                      xx!!!!!!!!!!xx                 oo                           |       *       ",
   "                                       xv|xxxxxxx!!x                oooo                                          ",
   "                                                xx!x               oooooo                               =         ",
   "                                                 x!x                                          xxxxxxxxxxxxxxxxx   ",
   "                                                 xvx     x   x     xx   xxx                     =!!!!!!!!!!!!!!xx ",
   "                                                         x   xx      |       xx           xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                         x    xx!!!!!!!!!!!xx            v                        ",
   "                                        x                     xxxx!!!!!xxxx                                       ",
   "                                        x      x     x            xxxvxxx        xxx         xxx                  ",
   "                                               x  +  x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x|    x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "         ff                                    x     x      o  o     x   x         x         x                    ",
   "        fffff                 xxx   xxx        x     x               x   x         x         x                    ",
   "                                x   x          x    |x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "                 ff             x   x           x     x      o  o     x   x         x         x                   ",
   "               fffff            x o x          x    xx               x   x   x               x                    ",
   "     @                          x   x          x     x               x   x   x               x                    ",
   "    xxx             +           x   x          x     x               x   xxxxx      xxx      x                    ",
   "    x x           xxxx         xx o xx         x     x               x       o  y   x x         x                 ",
   "!!!!x x!!!!!!!!!!!!!!x   !!!!!!    xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx              ",
   "!!!!x x!!!!!!!!!!!!!!x   !!!!!x    o                          xx!!!!!!xx !                    xx     xx           ",
   "!!!!x x!!!!!!!!!!!!!!x           !!!!!x                     xx!!!!!!xx  !                     xxxxxxx             ",
   "!!!!x x!!!!!!!!!!!!!!x    xxxxxxxxxxxxxx!!!!!!xx   !                                                              ",
   "!!!!x x!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                             ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                             "],
  ["                                        f                                                                     ",
   "                                       fff                                                                    ",
   "                                       fffff                                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        *                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x       xx         yxy   ++     x   xxx                              ",
   "                                       x x        x          x  oooo    x                                     ",
   "                                      xx xxx      x          x   oooo   x|                                    ",
   "                             x        x   x       x          x   oooo   x       xxx                           ",
   "                             x        x   x                  x    yy    x      x!!!x                          ",
   "                             x        x   x                  xxxxxxxxxxxx       xxx                           ",
   "                             x        x   xx      x   x      x                                                ",
   "                             x        x   xxxxxxxxx   xxxxxxxx              x                                 ",
   "                                      x   xooooooooooox                    x                                  ",
   "                                      x   xooooooooooox                     xx                                ",
   "                                      x   xooooooooooox                                                       ",
   "                             x        x   x |     =    x           xxx                                        ",
   "                             x        x   x           x           x!!!x                 xxx                   ",
   "                             x        x   x     |    |x     o      xxx       xxxx                             ",
   "                                      x   x           x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xx v   |  x!!!x                  ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x        x        x!!!x                  ",
   "                             xxxxxxxxxxxxxx          x!!!!!!!!!!!!!!!x         x          v                   ",
   "                             x               y xxxxxxxxxxxxxxxxxxxxxxx        x      x                        ",
   "                              x           x          ff    v                         xxxx                      ",
   "  xxx                         x     x     x                                         xxxx                 xxx  ",
   "  x x                         x    xxx    x          o          o                      xxx               x x  ",
   "  x                           x    xxx    xxxxxxx   o*o        oyo          xxxxx                          x  ",
   "  x                           x           x          o          o          x   x                           x  ",
   "  x                  +          xx          x                              x x x                             x",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x |   |                         xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx         =                        x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxx+ x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "             x      x    xxxxxxx   x     x                                  y                                 ",
   "              x    x     x     x   x     x                                                                    ",
   "               x  x      x     x   x  @  x                         y                                          ",
   "                x        x     x   x     x              y                                                     ",
   "                x        x     x   x     x                                     y                              ",
   "                x        xxxxxxx   xxxxxxx                                                                    ",
   "                                                                                                              ",
   "                           y                                                                                  ",
   "                y                              y                                                              ",
   "                                                          +++                                                 ",
   "                                  x             x  x    xxxxxxx                                               ",
   "                                   x           x   x    x     x                                               ",
   "                                    x    x    x    x    x     x                                               ",
   "                                      x x  x x     x    x     x          y                                    ",
   "                   y                   x    x      x    x     x                                               ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                         y                                                                    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "             ++                                                                                               ",
   "            +++                                                                                               ",
   "          +++++                                                                                               ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
